[package]
name = "docked"
version = "refs/tags/v0.0.4"
authors = ["dunlord"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
